language: ruby

rvm:
 - 2.7.0

os:
- osx

cache: bundler

services: 
- postgresql

before_install:
- gem update —system
- gem install bundler

script:
- bundle exec rake db:create
- bundle exec rake db:migrate
-  bundle exec rspec spec